#!/bin/sh
### script to run one job

### Set the job name
#PBS -N REPLACE_JOB_NAME

### Join the standard output and standard error streams
#PBS -j oe

### Specify wallclock time required for this job, hhh:mm:ss
#PBS -l walltime=01:00:00

### set directory for job execution
cd ~jch/jch-sREPLACE_NUMBER

### record the date, then time your executable program
date
/usr/bin/time ./REPLACE_EXECUTABLE_NAME "8000" "$1"
