#! /bin/sh

if [ $# != 2 ]; then
  cat README
else
rm -f *.o* 
  if [ $1 == "-long" ] || [ $1 == "-all" ]; then
    for i in `seq 1 $2`;
    do
      qsub -v OMP_NUM_THREADS=1 -l select=1:ncpus=1 ./run -F "1"
      qsub -v OMP_NUM_THREADS=2 -l select=1:ncpus=2 ./run -F "2"
    done
  fi
    
  if [ $1 == "-short" ] || [ $1 == "-all" ]; then
    for i in `seq 1 $2`;
    do
      qsub -v OMP_NUM_THREADS=5 -l select=1:ncpus=5 ./run -F "5"
      qsub -v OMP_NUM_THREADS=10 -l select=1:ncpus=10 ./run -F "10"
      qsub -v OMP_NUM_THREADS=20 -l select=1:ncpus=20 ./run -F "20"
      qsub -v OMP_NUM_THREADS=30 -l select=1:ncpus=30 ./run -F "30"
    done
  fi
fi
